### ISSUE TITLE
Hassio won't load add-on

### ISSUE THREAD

**Issue by 530projects** [rs1932/ring-alarm-hassio-addon#2]
I successfully installed this add-on about 2 weeks ago and everything worked great. Today, I am trying to install the add-on on a fresh install of Hassio on a raspberry pi 3b, and now I get this error:

19-04-11 23:05:39 INFO (MainThread) [hassio.addons.git] Clone add-on https://github.com/rs1932/ring-alarm-hassio-addon repository
19-04-11 23:05:40 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/git/5e5dfff6/config.json: required key not provided @ data['arch']. Got None
19-04-11 23:05:40 INFO (MainThread) [hassio.addons] Load add-ons: 55 all - 0 new - 0 remove

**Comment by hjanum** [comment]
@530projects this is because the arch tag is missing in the setup. It is required by newer versions of Hass.io.
I have added it as a pull request about 8 days ago, but it has not been merged in yet.

In the meantime you can use this one:
https://github.com/hjanum/ring-alarm-hassio-addon

**Comment by 530projects** [comment]
I thought that was the case when I saw your pull request. I just wasn't sure how to use it. 

I tried using the link you had and this is the error I get: "This addon is not available on your system."

So I don't think that is the correct arch for the pi 3b.

**Comment by hjanum** [comment]
Try it again. I added more arch's.
Initially, I only added what I needed myself :-)

**Comment by rs1932** [comment]
Thanks, hjanum. Merged ur changes.
