### ISSUE TITLE
No clue how to add this to hassio

### ISSUE THREAD

**Issue by Grey-Lancaster** [rs1932/ring-alarm-hassio-addon#3]
Any help for this NOOB?
Thanks,
Grey

**Comment by gbdavidx** [comment]
copy https://github.com/rs1932/ring-alarm-hassio-addon and put it in the Add URL section of repositories, then install on the very bottom, not that hard bro

**Comment by Grey-Lancaster** [comment]
Thanks, I had actually added the url once but did not find it at the bottom :(
Mow that it is started I have to figure out what it does !!
Thanks,
Grey

**Comment by dyennam** [comment]
@Grey-Lancaster 
Hi, did you get it work. I am getting some long from my MQTT broker. But i dont see any ring devices in my states.
This is my config.yaml
`mqtt:
  broker: 192.168.1.xxx:1833
  Username: mqttUSER
  Password: mqttPASS
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 0
    retain: false
  `

**Comment by Grey-Lancaster** [comment]
Are you using an mqtt broker other than the HASSIO addin ? username and password are lowercase and I am using 127.0
`mqtt:
  broker: 127.0.0.1
  username: mqttuser
  password: mqttpass
  discovery: true
  discovery_prefix: homeassistant
  
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 0
    retain: false  

  will_message:
    topic: 'hass/status'
    payload: 'offline'`

**Comment by dyennam** [comment]
@Grey-Lancaster Thanks for the previous answer (capital letter fix helped me out. Thanks). But i have a few follow up questions. Sorry for the wall of text.
For Mqtt i am using this: https://www.home-assistant.io/addons/mosquitto/
Ring hassio Addon Config:
`{
  "host": "192.168.1.235",
  "port": 1883,
  "ring_topic": "ring",
  "hass_topic": "hass/status",
  "mqtt_user": "mqttuser",
  "mqtt_pass": "mqtt",
  "ring_user": "dyennam@gmail.com",
  "ring_pass": "Dheeraj77"
}`
After enabling logs, i am getting some values that reflect the output of the 
For example: On the ring hassio integration logs:
`2019-06-01T06:47:25.036Z ring-alarm-mqtt HASS config topic: homeassistant/binary_sensor/3d270e4d-7e77-4419-4aad-799d5c081e78/9ace21fa-1bcf-4f50-9db6-fd4b31192982/config
2019-06-01T06:47:25.036Z ring-alarm-mqtt { name: 'Ring Contact Sensor 58750',
  unique_id: '9ace21fa-1bcf-4f50-9db6-fd4b31192982',
  availability_topic: 'ring/alarm/3d270e4d-7e77-4419-4aad-799d5c081e78/status',
  payload_available: 'online',
  payload_not_available: 'offline',
  state_topic:
   'ring/alarm/3d270e4d-7e77-4419-4aad-799d5c081e78/binary_sensor/9ace21fa-1bcf-4f50-9db6-fd4b31192982/state',
  json_attributes_topic:
   'ring/alarm/3d270e4d-7e77-4419-4aad-799d5c081e78/binary_sensor/9ace21fa-1bcf-4f50-9db6-fd4b31192982/attributes',
  device_class: 'door' }`

Below is my MQTT broker setup. Are you using another kind of mqtt broker? 
`{
  "logins": [
    {
      "username": "mqttuser",
      "password": "mqttpass"
    }
  ],
  "anonymous": false,
  "quiet_logs": true,
  "customize": {
    "active": false,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}`
Logs on the MQTT Broker:
`1559371645: |-- aclcheck(mqttuser, homeassistant/binary_sensor/3d270e4d-7e77-4419-4aad-799d5c081e78/725867c1-aa4f-4470-97b3-3a88ee33d1ad/config, 2) SUPERUSER=Y by http
1559371645: |--  Cached  [BE176DB166A3E50670343C21E246AF1FFB15396A] for (client id not available,mqttuser,2)
1559371645: |-- mosquitto_auth_acl_check(..., client id not available, mqttuser, homeassistant/binary_sensor/3d270e4d-7e77-4419-4aad-799d5c081e78/ea42e928-7785-40e2-9d39-668c942593a0/config, MOSQ_ACL_WRITE)
1559371645: |-- url=http://127.0.0.1:8080/superuser
1559371645: |-- data=username=mqttuser&password=&topic=&acc=-1&clientid=
1559371645: |-- aclcheck(mqttuser, homeassistant/binary_sensor/3d270e4d-7e77-4419-4aad-799d5c081e78/ea42e928-7785-40e2-9d39-668c942593a0/config, 2) SUPERUSER=Y by http
1559371645: |--  Cached  [2BA508622381E9B41236D4DB941C818E2BB36934] for (client id not available,mqttuser,2)`

So my events are going though the mqtt broker. But i am not able to see any new states.
could you please tell me how you were configuring your UI. or did you add any new config related to the mqtt. If you don't mind, could you please post your config for mqtt broker, hassio addon, and config.yaml along with one of the lovelace yaml snipper please.

In my configuration.yaml i have the below for mqtt:
`mqtt:
  broker: 192.168.1.235:1833 # tried this with 127.0.0.1 but it was same result no change.
  client_id: hass_mqtt
  username: mqttuser
  password: mqtt
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 0
    retain: false
  will_message:
    topic: 'hass/status'
    payload: 'offline'    `

**Comment by Grey-Lancaster** [comment]
Look  way down in this one for tslighter did a quick install on hassio the entries are formated properly which I can not figure out how to paste
yes that is the mqtt broker but you do not put a port ?
https://community.home-assistant.io/t/ring-alarm-integration-via-mqtt/102105/76

PS edit your above post and remove your ring username and password  then delete the original post, then go to ring.com and change your password :)

**Comment by dyennam** [comment]
@Grey-Lancaster 
Thanks for url, Got it working after a few restarts of hassio.
Only thing left is I need a way to figure out how to add the keypad on lovelace so that the user has to input a code to change states.

Thanks for the password check, I thought i did remove it but apparently i didn't.

**Comment by Grey-Lancaster** [comment]
no idea on the keypad but to get into hassio you need a password?

**Comment by dyennam** [comment]
Nope, more like if you try to change the state of the RING alarm, ask for a 4 digit code or something. Especially when disarming it via a non-admin user or something.
